"""initial

Revision ID: 125782e6d6fc
Revises: 
Create Date: 2022-11-10 11:05:57.851314

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '125782e6d6fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(roles_table, [
        {'id':1,'name':'Грузчик'},
        {'id':2,'name':'Дворник'},
    ])

    users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.Text(), nullable=True),
    sa.Column('datar', sa.Date(), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
